{"test_id": "scenario8_test_20250702_131924_8751c88c_test1_days_seq", "batch_id": "scenario8_test_20250702_131924_8751c88c_test1_days_seq_batch_001", "worker_id": "main", "request_name": "Batch 1", "start_time": "2025-07-02T13:19:24.598550", "end_time": "2025-07-02T13:19:29.480695", "duration_seconds": 4.882144451141357, "status_code": 500, "success": false, "data_points": 53760, "response_size": 0, "error_message": "('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))"}
